### PR TITLE
openjdk11 testing

### PR DESCRIPTION
**Pull request by eed3si9n**
Ref https://github.com/sbt/io/issues/85
Ref https://github.com/sbt/io/issues/174

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=pull/181/head&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=pull/181/head&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=pull/181/head&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by eed3si9n** [comment]
```
[info] - should relativize *** FAILED ***
[info]   Some(meh.file) was not equal to Some(../../meh.file) (IOSpec.scala:25)

[info] ! IO.IO.classLocationFile able to determine containing directories: Falsified after 0 passed tests.
```

confirming https://github.com/sbt/io/issues/85

**Comment by eatkins** [comment]
That meh.file test should be fixed if #175 is merged into develop.

**Comment by eed3si9n** [comment]
@eatkins See https://github.com/sbt/io/pull/183. I think we should avoid `File#getCanonicalFile` since it has unwanted side effect of resolving the symbolic links, which could be affecting tests on macOS since temp directories are in `/var`, which goes to `/private/var`; or expanding the symbolic link during directory copy etc.

**Pull request merged**
