### PR TITLE
Make specifying the jar/zip timestamp independent of timezone

### PR DESCRIPTION
**Pull request by raboof**
This change does not break existing behavior because the methods taking a `time` parameter aren't used anywhere yet, and this is the right thing to do for https://github.com/sbt/sbt/pull/5233

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=pull/280/head&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1841/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1842/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-develop-pull/280/head-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1841/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@4c1f7a754806b96e2ad8ca964c3d634606036f3c
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@37665fc007614ec7261588fde914bc477a1b0907
  io                | <A HREF="https://github.com/sbt/io/pull/280">pull/280/head       </A> | sbt/io@07c2c3017cf7cd23cd47968be79a8f8fa1fb0e2f
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@574be6fb792e5dca0c7ff3668902776148584eaf
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@098796cdff7305a4aaadea9fdbba7fb6c23ff3ed

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=develop&io=pull/280/head&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/5233/head-develop-pull/280/head-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1842/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/5233">pull/5233/head      </A> | sbt/sbt@c53b2b0f7472ebea21cd28d23a457a2f7e17afdf
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@37665fc007614ec7261588fde914bc477a1b0907
  io                | <A HREF="https://github.com/sbt/io/pull/280">pull/280/head       </A> | sbt/io@07c2c3017cf7cd23cd47968be79a8f8fa1fb0e2f
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@574be6fb792e5dca0c7ff3668902776148584eaf
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@098796cdff7305a4aaadea9fdbba7fb6c23ff3ed

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/5233/head&zinc=develop&io=pull/280/head&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
