### PR TITLE
Fix tests on windows, closes #52

### LINKED ISSUE #52: `sbt.io.IOSpec` and `sbt.io.PathMapperSpec` fail on Windows
I set up appveyor to benchmark file watching on Windows, and noticed that these two test suites fail on Windows:

 - `sbt.io.IOSpec`
 - `sbt.io.PathMapperSpec`

Build output: https://ci.appveyor.com/project/Duhemm/io/build/2

### PR DESCRIPTION
**Pull request by OlegYch**
replaces stringly paths comparison with file-based

### CODE REVIEW

**Comment by OlegYch** [comment]
test failure seems unrelated and introduced earlier in 49e8c80

**Review by dwijnand — APPROVED** [review]
Thanks!

**Comment by eatkins** [comment]
I re-ran the flaky test. I believe the flakiness is resolved by #155.

**Comment by eatkins** [comment]
It would be great to add a .appveyor.yml so that we'd run tests against windows as part of CI. I think it would be fine to just test windows on 2.12.x. I'm working on some updates to swoval and have found it useful to have automated windows testing (which otherwise tends to get forgotten).

**Pull request merged**
