### PR TITLE
[DO NOT MERGE] just to produce a SNAP release from Jenkins

### PR DESCRIPTION
**Pull request by andreaTP**
This is a backport just to be able to run Jenkins.

We can close this as soon as https://github.com/sbt/sbt-validator/pull/34
get merged

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=pull/200/head&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1127/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1128/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1129/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-develop-pull/200/head-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1128/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@23063e2813c81daee64d31dd7760f5a4fae392e6
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@c8e1f5335552bae9a7623d92866a233598fad9fc
  io                | <A HREF="https://github.com/sbt/io/pull/200">pull/200/head       </A> | sbt/io@21742bf69841f8407ed449815be73bfa15a49f8e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@c53aa4a6df91154c7e88e64c8c6adbcd2f0020a3
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@cd679591d068c9863919feea4f363070c74f2774

:white_check_mark: The result is: ***SUCCESS***

The binaries are at https://dl.bintray.com/sbt/maven-snapshots
The new sbt version is: 1.3.0-bin-20181024T144016
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=develop&io=pull/200/head&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4430/head-develop-pull/200/head-pull/270/head-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1129/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4430">pull/4430/head      </A> | sbt/sbt@bf90f35e5e9f07ec6d5ca4318d52e6b2f1f93e37
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@c8e1f5335552bae9a7623d92866a233598fad9fc
  io                | <A HREF="https://github.com/sbt/io/pull/200">pull/200/head       </A> | sbt/io@21742bf69841f8407ed449815be73bfa15a49f8e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/270">pull/270/head       </A> | sbt/librarymanagement@abc6d6927156970ab858285a71e7ad269be2f5cf
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@cd679591d068c9863919feea4f363070c74f2774

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4430/head&zinc=develop&io=pull/200/head&librarymanagement=pull/270/head&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1131/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4430/head-develop-pull/200/head-pull/270/head-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1131/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4430">pull/4430/head      </A> | sbt/sbt@bf90f35e5e9f07ec6d5ca4318d52e6b2f1f93e37
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@c8e1f5335552bae9a7623d92866a233598fad9fc
  io                | <A HREF="https://github.com/sbt/io/pull/200">pull/200/head       </A> | sbt/io@21742bf69841f8407ed449815be73bfa15a49f8e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/270">pull/270/head       </A> | sbt/librarymanagement@abc6d6927156970ab858285a71e7ad269be2f5cf
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@cd679591d068c9863919feea4f363070c74f2774

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4430/head&zinc=develop&io=pull/200/head&librarymanagement=pull/270/head&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1133/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: pull/4430/head-develop-pull/200/head-pull/270/head-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1133/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/pull/4430">pull/4430/head      </A> | sbt/sbt@8a8e33ba63250fed4884e7c5dfedeb23375bdd5a
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@c8e1f5335552bae9a7623d92866a233598fad9fc
  io                | <A HREF="https://github.com/sbt/io/pull/200">pull/200/head       </A> | sbt/io@21742bf69841f8407ed449815be73bfa15a49f8e
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/pull/270">pull/270/head       </A> | sbt/librarymanagement@abc6d6927156970ab858285a71e7ad269be2f5cf
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@cd679591d068c9863919feea4f363070c74f2774

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=pull/4430/head&zinc=develop&io=pull/200/head&librarymanagement=pull/270/head&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by eed3si9n** [comment]
Closing this since https://github.com/sbt/sbt-validator/pull/34 is merged.

**Pull request closed without merging**
