### PR TITLE
allow setting the timestamp for jars, sort entries by name

### PR DESCRIPTION
**Pull request by raboof**
To allow making builds more reproducible/deterministic.

The changes in this PR are safe because the behavior doesn't change until the calling code switches to the new functions.

(This is a rebase of #58, but it appears github doesn't let you reopen PR's against deleted branches, and also doesn't let you retarget closed PR's...)

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=pull/279/head&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1830/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-develop-pull/279/head-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1830/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@08c7fd1b8f69d9f8d6704131811f10787eb016d0
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@37665fc007614ec7261588fde914bc477a1b0907
  io                | <A HREF="https://github.com/sbt/io/pull/279">pull/279/head       </A> | sbt/io@605d9084966ddff1769d5adc7cc3d8658ed660d7
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@574be6fb792e5dca0c7ff3668902776148584eaf
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@098796cdff7305a4aaadea9fdbba7fb6c23ff3ed

:x: The result is: ***FAILED***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=develop&io=pull/279/head&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1832/console">is in progress...</a>

**Comment by typesafe-tools** [comment]
[//]: # (Refs: develop-develop-pull/279/head-develop-develop)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/1832/">has checked</A> the following projects, tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/develop">develop             </A> | sbt/sbt@08c7fd1b8f69d9f8d6704131811f10787eb016d0
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/develop">develop             </A> | sbt/zinc@37665fc007614ec7261588fde914bc477a1b0907
  io                | <A HREF="https://github.com/sbt/io/pull/279">pull/279/head       </A> | sbt/io@605d9084966ddff1769d5adc7cc3d8658ed660d7
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/develop">develop             </A> | sbt/librarymanagement@574be6fb792e5dca0c7ff3668902776148584eaf
  util              | <A HREF="https://github.com/sbt/util/tree/develop">develop             </A> | sbt/util@098796cdff7305a4aaadea9fdbba7fb6c23ff3ed

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=develop&zinc=develop&io=pull/279/head&librarymanagement=develop&util=develop&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
