### PR TITLE
Add option preserveExecutable to IO.copyFile and IO.copyDirectory

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes sbt/sbt#944

Forward port of
https://github.com/sbt/sbt/commit/1e61b9acf34b7d89a54a5adc021cc37cd3ecd0ef

Part of https://github.com/sbt/sbt/issues/2384

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?io=pull/53/head&deploy_to_bintray=false">THIS LINK.</A>

**Review by eed3si9n — CHANGES_REQUESTED** [review]
Default params made it impossible to evolve the old IO. We should learn from that and add overloads here.

**Comment by dwijnand** [comment]
You can evolve by just appending to the end.

These methods have 3 optional booleans, how would you like to overload them?

**Comment by eed3si9n** [comment]
```scala
def copy(sources: Traversable[(File, File)]): Set[File]
def copy(sources: Traversable[(File, File)], options: CopyOption): Set[File]
def copy(sources: Traversable[(File, File)],
      overwrite: Boolean,
      preserveLastModified: Boolean,
      preserveExecutable: Boolean): Set[File] 
```

where CopyOption is defined using Contraband.

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt%20validator/parambuild/?io=pull/53/head&deploy_to_bintray=false">THIS LINK.</A>

**Comment by dwijnand** [comment]
@eed3si9n Done, but I'm concerned about the impact it has on users migrating from sbt 0.13 to sbt 1... Lemme know.

**Review by eed3si9n — APPROVED** [review]
Perfect

**Comment by eed3si9n** [comment]
There might be some source breakages if ppl relied on the default params, but I think we did the best we can to make this evolvable, so I think it's an okay compromise.

**Pull request merged**
