### PR TITLE
Make IO.classfileLocation consistent

### PR DESCRIPTION
**Pull request by eatkins**
I have been having trouble getting the sbt tests to pass (both scripted
and runProj/test) since #185. The big problem that I've been running
into is that for some classes IO.classfileLocation returns a full
absolute path to the class file* while for others it returns just the
base directory of the class file. In this commit, I rework
classfileLocation to just turn the base directory (or jar file) for the
class. It is then up to the user to append the class name if necessary.
A separate PR in zinc is necessary to adapt this logic.

* There are effectively two cases: class files in a directory and class
files in a jar. The former should be url with the format:
file:$ABSOLUTE_PATH_TO_CLASS_FILE
while the latter shoud have the format:
jar:file:$ABSOLUTE_PATH_TO_JAR!/${RELATIVE_CLASS_FILE_NAME}

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=pull/188/head&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Comment by eatkins** [comment]
The zinc PR https://github.com/sbt/zinc/pull/603 requires this change.

**Comment by eed3si9n** [comment]
Trying to dig through the history.

- https://github.com/sbt/sbt/pull/2214 / https://github.com/sbt/io/pull/13 adds `ClassLoader.getSystemClassLoader` support.
- https://github.com/sbt/sbt/pull/2268 / https://github.com/sbt/io/pull/15 fixes it for static inner class. (https://github.com/sbt/sbt/issues/2263#issuecomment-155428549) That created `classfileLocation` (the one that returns location to the classfile), and `classLocationFile` the one that returns the directory.
- sbt 0.13 bincompat fix up https://github.com/sbt/sbt/pull/2342
- I broke these in #181  c7bd75b34619a73bd5138b1338fd39a181a7c662 when I mixed `classLocationFile` and `classfileLocation`.

**Review by eed3si9n — CHANGES_REQUESTED** [review]
I messed up in https://github.com/sbt/io/pull/181.
We need to re-split the implementation of classLocationFile and classfileLocation. Probably a good idea to add tests.

**Comment by eatkins** [comment]
Cool. To be honest, my motivation is just to get https://github.com/sbt/sbt/pull/4335 out the door. The scripted tests fail due to #181. I'll take a look at the referenced commits when I get a chance, but if you get your own fix in ahead of me, I'll happily review it for you.

**Comment by eed3si9n** [comment]
Hopefully I'll get around to it today.

**Comment by eed3si9n** [comment]
Closing this in favor of https://github.com/sbt/io/pull/189

**Pull request closed without merging**
