### PR TITLE
Fix #86: prevent concurrent modification of keysWithEvents map

### LINKED ISSUE #86: File modification events are getting lost in PollingWatchService
While investigating https://github.com/sbt/sbt/issues/3775 I think I have narrowed the bug down to the interaction between `PollingWatchService.pollEvents` and `PollingWatchService.PollingThread.addEvent`. 

Events often get lost without being properly consumed (https://github.com/sbt/io/issues/82 is probably related). 

**UPDATE**: the conclusion below is wrong, see comments further down.

As far as I understand the only reason that could happen is if some events get added between these two statements: 

https://github.com/sbt/io/blob/e8c9757799bb0b251e5c5aefd96f841428d0eb9a/io/src/main/scala/sbt/io/PollingWatchService.scala#L61-L64

so `thread.keysWithEvents.clear` deletes events that weren't consumed. This should be prevented by the `synchronized` guard.

It is difficult to set up my own modified sbt build to properly test this but at a glance I find this line suspicious:

https://github.com/sbt/io/blob/e8c9757799bb0b251e5c5aefd96f841428d0eb9a/io/src/main/scala/sbt/io/PollingWatchService.scala#L105

I don't understand the purpose of the `notifyAll` call at this point and I suspect that it could break the intended synchronization behaviour.

### PR DESCRIPTION
**Pull request by mechkg**

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?io=pull/89/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

**Comment by typesafe-tools** [comment]
A validation involving this pull request <a href="https://jenkins.scala-sbt.org:8592/job/sbt-validator/291/console">is in progress...</a>

**Review by dwijnand — CHANGES_REQUESTED** [review]
Hi @mechkg,
Thank you for the PR. I just verified that this also fixes https://github.com/sbt/sbt/issues/3687. Perhaps also https://github.com/sbt/sbt/issues/3695.

This is failing MiMa, but from some testing I think it's because MiMa doesn't properly understand private inner classes. Could you add a MiMa exclusion for the changed constructor, please?

Also, could you rebase so this can be merged into the 1.0.x branch? Perhaps we can release sbt 1.0.5.

**Comment by mechkg** [comment]
I'm afraid I have no idea what MiMa is and how to add an exclusion. It would probably be easier if you reject this PR and make the changes yourself. It is only a couple of lines.

**Comment by typesafe-tools** [comment]
[//]: # (Refs: 1.x-1.x-pull/89/head-1.x-1.x-1.x)
The validator <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/291/">has checked</A> the following projects against Scala 2.12,
tested using dbuild, projects built on top of each other.

Project             | Reference            | Commit
:------------------ | :------------------- | :----------------
  sbt               | <A HREF="https://github.com/sbt/sbt/tree/1.x">1.x                 </A> | sbt/sbt@c02baa177e9ff47566a7172183911312b95899e1
  zinc              | <A HREF="https://github.com/sbt/zinc/tree/1.x">1.x                 </A> | sbt/zinc@366eaffc6d93586d7bed7870493d2579bdb2600d
  io                | <A HREF="https://github.com/sbt/io/pull/89">pull/89/head        </A> | sbt/io@c1ace4e5c300bb13333c2a898ba481f317f7ffbd
  librarymanagement | <A HREF="https://github.com/sbt/librarymanagement/tree/1.x">1.x                 </A> | sbt/librarymanagement@1ad2ff929577ab70b78305ecaab518db9a44952f
  util              | <A HREF="https://github.com/sbt/util/tree/1.x">1.x                 </A> | sbt/util@83f8eabfabed83156582278905fd3af6108d3390
  website           | <A HREF="https://github.com/sbt/website/tree/1.x">1.x                 </A> | 

:white_check_mark: The result is: ***SUCCESS***
<A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild?sbt=1.x&zinc=1.x&io=pull/89/head&librarymanagement=1.x&util=1.x&website=1.x&deploy_to_bintray=false&run_sbt_community=false">(restart)</A>

**Pull request closed without merging**
