### PR TITLE
Update IO.toURI to avoid syscalls

### PR DESCRIPTION
**Pull request by jtjeferreira**
same as https://github.com/eed3si9n/sjson-new/pull/117/files

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=pull/309/head&librarymanagement=develop&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Review by eatkins — APPROVED** [review]
LGTM. I had actually noticed `Path.toUri` showing up in some sbt flamegraphs a while back.

**Comment by eed3si9n** [comment]
I feel like I should add unit tests on sjson-new to check various corner cases before propagating the impl. Overall I'm +1 on avoiding stat calls.

**Comment by eed3si9n** [comment]
Closing this in favor of https://github.com/sbt/io/pull/313

**Pull request closed without merging**
